apiVersion: v1
kind: Pod
metadata:
  name: bq-viz-pipeline
  namespace: viz-pipeline
spec:
  containers:
  - image: {{CONTAINER_NAME}}
    command: ["/bin/bash"]
    args: ["./run_bq.sh", "-m", "{{API_MODE}}"]
    imagePullPolicy: IfNotPresent
    name: bq-viz-pipeline
  restartPolicy: Always