apiVersion: v1
kind: Pod
metadata:
  name: bt-viz-pipeline
  namespace: viz-pipeline
spec:
  containers:
  - image: {{CONTAINER_NAME}}
    command: ["/bin/bash"]
    args: ["./run_bt.sh", "-m", "{{API_MODE}}"]
    imagePullPolicy: IfNotPresent
    name: bt-viz-pipeline
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /keys/service_account_key.json
      - name: KEY_FILE
        value: /keys/service_account_key.json
      - name: PROJECT
        value: {{PROJECT}}
      - name: API_MODE
        value: {{API_MODE}}
      - name: BIGTABLE_INSTANCE
        value: {{BIGTABLE_INSTANCE}}
      - name: STAGING_LOCATION
        value: {{STAGING_LOCATION}}
      - name: BIGTABLE_POOL_SIZE
        value: "{{BIGTABLE_POOL_SIZE}}"
  restartPolicy: Always