apiVersion: v1
kind: Pod
metadata:
  name: bt-viz-pipeline
  namespace: viz-pipeline
spec:
  volumes:
  - name: google-cloud-key
    secret:
      secretName: service-key
  containers:
  - image: {{CONTAINER_NAME}}
    command: ["/bin/bash"]
    args: ["./run_bt.sh", "-m", "{{API_MODE}}"]
    imagePullPolicy: IfNotPresent
    name: bt-viz-pipeline
    #Prometheus port
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: google-cloud-key
      mountPath: /keys
    envFrom:
    - configMapRef:
        name: viz-pipeline-env
  restartPolicy: Always