apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viz-pipeline
  labels:
    # Project ID
    app: viz-pipeline
spec:
spec:
  # Rollbacks are accomplished via the autodeploy meachanism, so no need to keep
  # around old configs and old ReplicaSets. They just use up kubernetes
  # resources and slow everything down.
  revisionHistoryLimit: 0
  #Run one instance
  replicas: 1
  template:
    metadata:
      labels:
        app: viz-pipeline
      annotations:
        prometheus.io/scrape: 'true'
        source: '{{GIT_BRANCH}}/{{GIT_COMMIT}}'
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: service-key
      #Container details
      containers:
        - name: viz-pipeline
          image: {{CONTAINER_NAME}}
          imagePullPolicy: Always

          #Prometheus port
          ports:
          - containerPort: 9090
          volumeMounts:
          - name: google-cloud-key
            mountPath: /keys
          envFrom:
          - configMapRef:
              name: viz-pipeline-env
